This is test code to check that the OO version of msed works correctly.
This code mirrors matlab code at foot of notebook.

In [16]:
import numpy as np
from simcoder.msedOO import msed

base_matrix = np.array([[0.2, 0.6, 0.2],[0.1, 0.7, 0.2],[0.2, 0.5, 0.3]])

data = np.array([[0.2, 0.5, 0.3],[0.2, 0.7, 0.1]])


base = msed(base_matrix)  # form the base simplex

dists = base.msed(data)

print(dists)

indices = np.argsort(dists,axis=0)     # lowest is first

print(dists)

print(indices)




[[0.00569509]
 [0.00835954]]
[[0.00569509]
 [0.00835954]]
[[0]
 [1]]


% Matlab code:

base_matrix = [ 0.2 0.6 0.2,
                0.1 0.7 0.2,
                0.2 0.5 0.3 ]

data = [ 0.2 0.5 0.3,
         0.2 0.7 0.1 ]


msedBase = msed_base(base_matrix);
dists = msedBase.msed(data);
dists
[~,ord] = sort(dists);
ord
